/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void random_quote() throws IOException {
        String quote = Quote.randomQuote("./src/test/resources/recentquotes.json");
        assertNotNull(quote);
    }

}
